extends: minicpmo_4_5_2npu_910c_cfm6_dit_mlp_graph_competition.yaml

stage_args:
  - stage_id: 0
    model_arch: MiniCPMO45OmniForConditionalGeneration
    engine_args:
      max_num_seqs: 4
      max_num_batched_tokens: 16384
  - stage_id: 1
    model_arch: MiniCPMO45OmniForConditionalGeneration
    engine_args:
      max_num_seqs: 4
      max_num_batched_tokens: 8192
  - stage_id: 2
    model_arch: MiniCPMO45Code2Wav
    engine_args:
      enforce_eager: true
    stage_connector_config:
      extra:
        token2wav_n_timesteps: 6
        npu_dit_mlp_graph: true
        npu_dit_mlp_graph_width: 50
        npu_virtual_concat_projection: true
